// web/src/app/page.tsx
import { PoolForm } from "@/components/PoolForm"
import { api } from "@/libs/axios"
import Image from "next/image"
import appPreviewImg from "../assets/app-nlw-copa-preview.png"
import iconCheckImg from "../assets/icon-check.svg"
import logoImg from "../assets/logo.svg"
import usersAvatarExampleImg from "../assets/users-avatar-example.png"

export default async function Home() {
  const poolCountResponse = await api.get("/pools/count")
  const poolCount = poolCountResponse.data.count

  const userCountResponse = await api.get("/users/count")
  const userCount = userCountResponse.data.count

  const guessCountResponse = await api.get("/guesses/count")
  const guessCount = guessCountResponse.data.count

  return (
    <div className="max-w-6xl h-screen mx-auto grid grid-cols-2 gap-28 items-center">
      <main>
        <Image src={logoImg} alt="Nlw Logo" />

        <h1 className="mt-14 text-white text-5xl font-bold leading-tight">
          Crie seu próprio bolão da copa e compartilhe entre amigos!
        </h1>

        <div className="mt-10 flex items-center gap-2">
          <Image src={usersAvatarExampleImg} alt="Avatares de usuários" />

          <strong className="text-nlwGray-100 text-xl">
            <span className="text-ignite-500">+{userCount}</span> pessoas já estão usando.
          </strong>
        </div>

        <PoolForm />

        <p className="mt-4 text-sm text-gray-300 leading-relaxed">
          Após criar seu bolão, você receberá um código único que poderá usar para convidar outras
          pessoas 🚀.
        </p>

        <div className="mt-10 pt-10 mb-10 border-t border-gray-600 flex justify-between items-center text-gray-100">
          <div className="flex items-center gap-6">
            <Image src={iconCheckImg} alt="Icone de Check" />
            <div className="flex flex-col">
              <span className="font-bold text-2xl">+{poolCount}</span>
              <span>Bolões criados</span>
            </div>
          </div>

          <div className="w-px h-14 bg-gray-600" />

          <div className="flex items-center gap-6">
            <Image src={iconCheckImg} alt="Icone de Check" />
            <div className="flex flex-col">
              <span className="font-bold text-2xl">+{guessCount}</span>
              <span>Palpites enviados</span>
            </div>
          </div>
        </div>
      </main>

      <Image
        src={appPreviewImg}
        alt="Dois celulares exibindo uma prévia da aplicação móvel do NLW Copa"
        quality={100}
      />
    </div>
  )
}

// src/app/home/app.component.ts
import { HomeService } from './service/home.service';
import { Component } from '@angular/core';
import { NonNullableFormBuilder, Validators } from '@angular/forms';

interface HomeProps {
  count: number;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  numBolao!: number;
  numPaltites!: number;
  numUsuarios!: number;

  form = this.formBuilder.group({
    title: ['', Validators.required]
  });

  constructor(
    private homeService: HomeService,
    private formBuilder: NonNullableFormBuilder
  ){
    this.refresh();
  }

  refresh(){
    this.getNumBoloes();
    this.getNumPalpites();
    this.getNumUsuarios();
  }

  getNumBoloes(){
    this.homeService.getNumeroBolao().subscribe((response: HomeProps) => {
      this.numBolao = response.count;
    });
  }
  
  getNumPalpites(){
    this.homeService.getNumeroPalpites().subscribe((response: HomeProps) => {
      this.numPaltites = response.count;
    });
  }
  
  getNumUsuarios(){
    this.homeService.getNumeroUsuarios().subscribe((response: HomeProps) => {
      this.numUsuarios = response.count;
    });
  }

  onNovoBolao(){
    if(!this.form.valid){
      alert('Nome do bolão não pode ser vazio');
      return;
    }

    this.homeService.createBolao(this.form.value).subscribe({
      next: (response) => {
        console.log(response);
        const code = response.code;
        navigator.clipboard.writeText(code);
        alert(`Bolão criado com sucesso, o código do bolão é ${code}, e foi copiado para a área de transferência!`);
        this.refresh();
        this.form.reset();
      },
      error: (erro) => {
        console.error(erro);
        alert('Falha ao criar o bolão, tente novamente!');
      }
    });
  }
}

<div class="max-w-5xl h-screen mx-auto grid grid-cols-2 gap-28 items-center">
  <main>
    <img src="../../assets/logo.svg" alt="Logo NLW Copa">

    <h1 class="mt-14 text-white text-5xl font-bold leading-tight">
      Crie seu próprio bolão da copa e compartilhe entre amigos!
    </h1>

    <div class="mt-10 flex items-center gap-2">
      <img src="../../assets/avatares.png" alt="Users avatares image">
      <strong class="text-gray-100 text-xl">
        <span class="text-ignite-500">+{{ numUsuarios }}</span> pessoas já estão usando
      </strong>
    </div>

    <form class="mt-10 flex gap-2" [formGroup]="form">
      <input class="flex-1 px-6 py-4 rounded bg-gray-800 border-gray-600 text-sm text-gray-100" 
      type="text" placeholder="Qual nome do seu bolão?" formControlName="title">
      <button class="bg-yellow-500 px-6 py-4 rounded text-gray-900 font-bold text-sm uppercase hover:bg-yellow-700" (click)="onNovoBolao()">
        Criar novo bolão
      </button>
    </form>

    <p class="text-gray-300 mt-4 text-sm leading-relaxed">
      Após criar seu bolão, você receberá um código único que poderá usar para convidar outras pessoas 🚀.
    </p>

    <div class="mt-10 pt-10 border-t border-gray-500 text-gray-100 flex justify-between items-center">
      <div class="flex items-center gap-6">
        <img src="../../assets/icon-check.svg" alt="Icone de check">
        <div class="flex flex-col">
          <span class="font-bold text-2xl">+{{ numBolao }}</span>
          <span>Bolões criados</span>
        </div>
      </div>

      <div class="w-px h-14 bg-gray-600"></div>

      <div class="flex items-center gap-6">
        <img src="../../assets/icon-check.svg" alt="Icone de check">
        <div class="flex flex-col">
          <span class="font-bold text-2xl">+{{ numPaltites }}</span>
          <span>Palpites enviados</span>
        </div>
      </div>
    </div>
  </main>

  <img src="../../assets/app-nlw-copa-preview.png" alt="Dois celulares exibindo uma právia da aplicação movel do NLW Copa">
</div>
<router-outlet></router-outlet>
